name = "contact-form-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "contact-form-worker"

[vars]
ENVIRONMENT = "production"

# Add your email service API key as a secret:
# wrangler secret put EMAIL_API_KEY
# wrangler secret put RECIPIENT_EMAIL