name = "contact-form-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "contact-form-worker"

[vars]
ENVIRONMENT = "production"

# Rate limiting bindings
[[unsafe.bindings]]
name = "IP_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 1, period = 60 }

# Add your Mailgun credentials as secrets:
# wrangler secret put MAILGUN_API_TOKEN
# wrangler secret put RECIPIENT_EMAIL (optional)