[package]
name = "ezfilter-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
thiserror = "2.0"
