//! Plugin capabilities are **icanhaz grants**: the registry embeds
//! `icanhaz_broker::GrantStore` over the CEL environments `build.rs`
//! generated from `wit/world.wit`, one membrane per provider capability kind
//! (logger, annotator, local storage, clock). A plugin's granted provider
//! capability is issued as a grant when it is registered (which type-checks
//! its `allow` clause), held by the plugin as an `installed-app` principal,
//! and every resource method admits its call through that grant before doing
//! the work. Being grants, they list, narrow, certify and revoke like any
//! other authority icanhaz manages.
//!
//! Event capabilities (`handle-event`) are not grants: their `when` clause
//! runs against the event environment in [`crate::plugins::WitmPlugin::can_handle`].

use std::sync::{Arc, Mutex};

use icanhaz_broker::broker::bindings::icanhaz::nocap::types::{Principal, PrincipalKind};
use icanhaz_broker::broker::{GrantKind, GrantStore};

use crate::wasm::bindgen::witmproxy::plugin::capabilities::CapabilityKind;

/// A provider capability kind, as the grant store sees it.
#[derive(Debug, Clone, PartialEq)]
pub struct PluginKind(pub CapabilityKind);

impl GrantKind for PluginKind {
    fn tag(&self) -> &'static str {
        tag_of(&self.0).unwrap_or("event")
    }
    fn summarize(&self) -> String {
        self.0.to_string()
    }
    fn to_json(&self) -> serde_json::Value {
        serde_json::json!({ "kind": self.0.to_string() })
    }
    fn from_json(v: &serde_json::Value) -> Option<Self> {
        let kind = match v.get("kind")?.as_str()? {
            "logger" => CapabilityKind::Logger,
            "annotator" => CapabilityKind::Annotator,
            "local_storage" => CapabilityKind::LocalStorage,
            "clock" => CapabilityKind::Clock,
            _ => return None,
        };
        Some(PluginKind(kind))
    }
}

/// The registry's grant store, shared with every minted resource.
pub type Grants = Arc<Mutex<GrantStore<PluginKind>>>;

/// The store over the environments `build.rs` embedded.
pub fn builtin() -> anyhow::Result<GrantStore<PluginKind>> {
    static ENVS_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/ezcap-envs.json"));
    let membranes = ezcap::Membranes::from_json(ENVS_JSON, &[])
        .map_err(|e| anyhow::anyhow!("ezcap environments generated by build.rs: {e}"))?;
    Ok(GrantStore::with_membranes(membranes))
}

pub fn shared() -> anyhow::Result<Grants> {
    Ok(Arc::new(Mutex::new(builtin()?)))
}

/// Lock the store, recovering from a poisoned mutex (a panic while holding it
/// leaves the grants themselves consistent).
pub fn lock(grants: &Grants) -> std::sync::MutexGuard<'_, GrantStore<PluginKind>> {
    grants.lock().unwrap_or_else(|e| e.into_inner())
}

/// The principal a plugin's grants are held by.
pub fn principal(plugin_id: &str) -> Principal {
    Principal {
        kind: PrincipalKind::InstalledApp,
        id: plugin_id.to_string(),
        display_name: None,
    }
}

/// The membrane tag for a provider capability kind; `None` for event kinds.
pub fn tag_of(kind: &CapabilityKind) -> Option<&'static str> {
    match kind {
        CapabilityKind::Logger => Some("logger"),
        CapabilityKind::Annotator => Some("annotator"),
        CapabilityKind::LocalStorage => Some("local_storage"),
        CapabilityKind::Clock => Some("clock"),
        CapabilityKind::HandleEvent(_) => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::plugins::capabilities::Capability;
    use crate::wasm::bindgen::ezco::ezcap::types::Scope as ScopeWire;
    use crate::wasm::bindgen::witmproxy::plugin::capabilities::{
        Capability as WitCapability, EventKind,
    };
    use ezcap::{Call, Scope};
    use icanhaz_broker::broker::bindings::icanhaz::nocap::types::Denied;

    fn grants() -> Grants {
        shared().expect("embedded environments declare")
    }

    fn issue(grants: &Grants, kind: CapabilityKind, allow: &str) -> Result<String, Denied> {
        lock(grants).issue_scoped(
            PluginKind(kind),
            Scope::allow(allow),
            "test".to_string(),
            GrantStore::<PluginKind>::FOREVER,
            principal("@test/plugin"),
        )
    }

    fn cap(kind: CapabilityKind, allow: &str) -> Capability {
        Capability {
            inner: WitCapability {
                kind,
                scope: ScopeWire {
                    when: "true".to_string(),
                    allow: allow.to_string(),
                },
            },
            granted: true,
            when: None,
            token: None,
        }
    }

    #[test]
    fn every_provider_kind_has_an_environment() {
        let g = grants();
        for kind in [
            CapabilityKind::Logger,
            CapabilityKind::Annotator,
            CapabilityKind::LocalStorage,
            CapabilityKind::Clock,
        ] {
            assert!(issue(&g, kind, "true").is_ok(), "{kind}");
        }
        assert_eq!(
            tag_of(&CapabilityKind::HandleEvent(EventKind::Request)),
            None
        );
    }

    #[test]
    fn allow_is_type_checked_against_the_resource_interface() {
        let g = grants();
        assert!(
            issue(
                &g,
                CapabilityKind::LocalStorage,
                r#"call.args.key.startsWith("seen/")"#
            )
            .is_ok()
        );
        assert!(issue(&g, CapabilityKind::Logger, "state.calls < 100").is_ok());
        // `key` is a storage argument, not a logger one.
        assert!(matches!(
            issue(&g, CapabilityKind::Logger, r#"call.args.key == "x""#),
            Err(Denied::InvalidScope(_))
        ));
        // A provider kind with a clause that does not compile refuses the capability.
        let env = cel_cxx::Env::builder().build().expect("env");
        let mut c = cap(CapabilityKind::Clock, "call.args.nope == 1");
        assert!(
            c.compile_scope_expression(&env, &g, "@test/plugin")
                .is_err()
        );
        let mut c = cap(CapabilityKind::Clock, "state.calls < 10");
        assert!(c.compile_scope_expression(&env, &g, "@test/plugin").is_ok());
        let token = c.token.clone().expect("a grant");
        // The plugin holds it as an installed-app principal, listed like any grant.
        let listed = lock(&g).active_grants();
        assert!(
            listed
                .iter()
                .any(|v| v.id == token && v.holder == "@test/plugin"),
            "{listed:?}"
        );
    }

    #[test]
    fn admission_denies_with_a_sentence_and_revocation_cascades() {
        let g = grants();
        let token = issue(
            &g,
            CapabilityKind::LocalStorage,
            r#"call.args.key.startsWith("seen/")"#,
        )
        .expect("issue");
        let ok = || {
            Call::new("set")
                .arg("key", "seen/a")
                .arg("value", vec![1u8])
        };
        assert!(lock(&g).admit(&token, ok()).is_ok());
        let bad = Call::new("get").arg("key", "other/a");
        match lock(&g).admit(&token, bad) {
            Err(Denied::OutOfScope(s)) => assert_eq!(s, "key starts with “seen/”"),
            other => panic!("expected denial, got {other:?}"),
        }
        assert!(lock(&g).revoke(&token));
        assert!(matches!(
            lock(&g).admit(&token, ok()),
            Err(Denied::NotAuthorized)
        ));
    }

    #[test]
    fn recompiling_a_capability_replaces_its_grant() {
        let g = grants();
        let env = cel_cxx::Env::builder().build().expect("env");
        let mut c = cap(CapabilityKind::Logger, "true");
        c.compile_scope_expression(&env, &g, "@test/plugin")
            .expect("compile");
        let first = c.token.clone().expect("grant");
        // The user narrows the scope; the old grant is revoked, a new one issued.
        c.inner.scope.allow = r#"call.args.message.startsWith("[x]")"#.to_string();
        c.compile_scope_expression(&env, &g, "@test/plugin")
            .expect("recompile");
        let second = c.token.clone().expect("grant");
        assert_ne!(first, second);
        let call = || Call::new("info").arg("message", "hello");
        assert!(matches!(
            lock(&g).admit(&first, call()),
            Err(Denied::NotAuthorized)
        ));
        assert!(matches!(
            lock(&g).admit(&second, call()),
            Err(Denied::OutOfScope(_))
        ));
        let ok = Call::new("info").arg("message", "[x] hello");
        assert!(lock(&g).admit(&second, ok).is_ok());
    }
}
