//! Per-call admission for the provider capabilities (logger, annotator, local
//! storage, clock): one [`ezcap::Membrane`] per capability kind, over the CEL
//! environment `build.rs` generated from `wit/world.wit`. A plugin's granted
//! provider capability is minted as an instance here when it is registered
//! (which type-checks its `allow` clause), and every resource method admits
//! its call through that instance before doing the work.
//!
//! Event capabilities (`handle-event`) are not membranes: their `when` clause
//! runs against the event environment in [`crate::plugins::WitmPlugin::can_handle`].

use std::collections::HashMap;
use std::sync::Mutex;

use ezcap::{Call, CallEnv, CapabilityError, InstanceId, Membrane, Scope};

use crate::wasm::bindgen::witmproxy::plugin::capabilities::CapabilityKind;

pub struct Membranes {
    by_tag: Mutex<HashMap<String, Membrane>>,
}

impl Membranes {
    /// The environments `build.rs` embedded. Fails only if the generated
    /// environments do not declare, which a build could not have produced.
    pub fn builtin() -> anyhow::Result<Self> {
        static ENVS_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/ezcap-envs.json"));
        let envs: Vec<(String, CallEnv)> = serde_json::from_str(ENVS_JSON)
            .map_err(|e| anyhow::anyhow!("ezcap-envs.json (generated by build.rs): {e}"))?;
        let mut by_tag = HashMap::new();
        for (tag, env) in envs {
            let membrane = Membrane::new(env, &[]).map_err(|e| {
                anyhow::anyhow!("ezcap environment for `{tag}` does not declare: {e}")
            })?;
            by_tag.insert(tag, membrane);
        }
        Ok(Self {
            by_tag: Mutex::new(by_tag),
        })
    }

    /// The membrane tag for a provider capability kind; `None` for event kinds.
    pub fn tag_of(kind: &CapabilityKind) -> Option<&'static str> {
        match kind {
            CapabilityKind::Logger => Some("logger"),
            CapabilityKind::Annotator => Some("annotator"),
            CapabilityKind::LocalStorage => Some("local_storage"),
            CapabilityKind::Clock => Some("clock"),
            CapabilityKind::HandleEvent(_) => None,
        }
    }

    /// Mint an instance for `scope` under `tag`, type-checking the scope
    /// against the kind's interface.
    pub fn mint(&self, tag: &str, scope: &Scope) -> Result<InstanceId, String> {
        let mut by_tag = self.by_tag.lock().unwrap_or_else(|e| e.into_inner());
        let membrane = by_tag
            .get_mut(tag)
            .ok_or_else(|| format!("no admission environment for `{tag}`"))?;
        let cap = ezcap::Capability {
            kind: membrane.kind().clone(),
            scope: scope.clone(),
        };
        membrane.mint(&cap).map_err(|e| e.to_string())
    }

    /// Admit one call on an instance. A refusal carries the scope as sentences.
    pub fn admit(&self, tag: &str, id: &InstanceId, call: &Call) -> Result<(), CapabilityError> {
        let mut by_tag = self.by_tag.lock().unwrap_or_else(|e| e.into_inner());
        let membrane = by_tag.get_mut(tag).ok_or(CapabilityError::Unavailable)?;
        membrane.admit(id, call)
    }

    pub fn revoke(&self, tag: &str, id: &InstanceId) {
        let mut by_tag = self.by_tag.lock().unwrap_or_else(|e| e.into_inner());
        if let Some(membrane) = by_tag.get_mut(tag) {
            membrane.revoke(id);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::plugins::capabilities::Capability;
    use crate::wasm::bindgen::ezco::ezcap::types::Scope as ScopeWire;
    use crate::wasm::bindgen::witmproxy::plugin::capabilities::{
        Capability as WitCapability, EventKind,
    };

    fn membranes() -> Membranes {
        Membranes::builtin().expect("embedded environments declare")
    }

    fn cap(kind: CapabilityKind, allow: &str) -> Capability {
        Capability {
            inner: WitCapability {
                kind,
                scope: ScopeWire {
                    when: "true".to_string(),
                    allow: allow.to_string(),
                },
            },
            granted: true,
            when: None,
            instance: None,
        }
    }

    #[test]
    fn every_provider_kind_has_an_environment() {
        let m = membranes();
        for kind in [
            CapabilityKind::Logger,
            CapabilityKind::Annotator,
            CapabilityKind::LocalStorage,
            CapabilityKind::Clock,
        ] {
            let tag = Membranes::tag_of(&kind).expect("provider kind");
            assert!(m.mint(tag, &Scope::unrestricted()).is_ok(), "{tag}");
        }
        assert_eq!(
            Membranes::tag_of(&CapabilityKind::HandleEvent(EventKind::Request)),
            None
        );
    }

    #[test]
    fn allow_is_type_checked_against_the_resource_interface() {
        let m = membranes();
        assert!(
            m.mint(
                "local_storage",
                &Scope::allow(r#"call.args.key.startsWith("seen/")"#)
            )
            .is_ok()
        );
        assert!(m.mint("logger", &Scope::allow("state.calls < 100")).is_ok());
        // `key` is a storage argument, not a logger one.
        let err = m
            .mint("logger", &Scope::allow(r#"call.args.key == "x""#))
            .err();
        assert!(err.is_some(), "logger has no `key` argument");
        // A provider kind with a clause that does not compile refuses the capability.
        let env = cel_cxx::Env::builder().build().expect("env");
        let mut c = cap(CapabilityKind::Clock, "call.args.nope == 1");
        assert!(c.compile_scope_expression(&env, &m).is_err());
        let mut c = cap(CapabilityKind::Clock, "state.calls < 10");
        assert!(c.compile_scope_expression(&env, &m).is_ok());
        assert!(c.instance.is_some());
    }

    #[test]
    fn admission_denies_with_a_sentence_and_revocation_cascades() {
        let m = membranes();
        let id = m
            .mint(
                "local_storage",
                &Scope::allow(r#"call.args.key.startsWith("seen/")"#),
            )
            .expect("mint");
        let ok = Call::new("set")
            .arg("key", "seen/a")
            .arg("value", vec![1u8]);
        assert!(m.admit("local_storage", &id, &ok).is_ok());
        let bad = Call::new("get").arg("key", "other/a");
        match m.admit("local_storage", &id, &bad) {
            Err(CapabilityError::Denied(s)) => assert_eq!(s, "key starts with “seen/”"),
            other => panic!("expected denial, got {other:?}"),
        }
        m.revoke("local_storage", &id);
        assert!(matches!(
            m.admit("local_storage", &id, &ok),
            Err(CapabilityError::Unavailable)
        ));
    }

    #[test]
    fn recompiling_a_capability_replaces_its_instance() {
        let m = membranes();
        let env = cel_cxx::Env::builder().build().expect("env");
        let mut c = cap(CapabilityKind::Logger, "true");
        c.compile_scope_expression(&env, &m).expect("compile");
        let first = c.instance.clone().expect("instance");
        // The user narrows the scope; the old instance is revoked, a new one minted.
        c.inner.scope.allow = r#"call.args.message.startsWith("[x]")"#.to_string();
        c.compile_scope_expression(&env, &m).expect("recompile");
        let second = c.instance.clone().expect("instance");
        assert_ne!(first, second);
        let call = Call::new("info").arg("message", "hello");
        assert!(matches!(
            m.admit("logger", &first, &call),
            Err(CapabilityError::Unavailable)
        ));
        assert!(matches!(
            m.admit("logger", &second, &call),
            Err(CapabilityError::Denied(_))
        ));
        let ok = Call::new("info").arg("message", "[x] hello");
        assert!(m.admit("logger", &second, &ok).is_ok());
    }
}
