package witmproxy:plugin@0.0.5;

interface capabilities {
    use wasi:http/types@0.3.0-rc-2025-09-16.{request, response};

    // resource http-client {}
    // resource key-value-client {}
    // resource sql-client {}
    // resource queue-client {}

    /// A dumb and simple logging resource for debugging
    /// `TODO`: replace
    resource logger {
        info: func(message: string);
        warn: func(message: string);
        error: func(message: string);
        debug: func(message: string);
    }

    /// A resource for annotating/labeling content
    resource annotator-client {
        annotate: func(content: content);
    }

    /// A resource for storing small key-value pairs local to the plugin
    resource local-storage-client {
        set: func(key: string, value: list<u8>);
        get: func(key: string) -> option<list<u8>>;
        delete: func(key: string);
    }

    /// The provider for any requested capabilities, which are only present if granted by the user
    resource capability-provider {
        // http: func() -> option<http-client>;
        // kv: func() -> option<key-value-client>;
        // sql: func() -> option<sql-client>;
        // queue: func() -> option<queue-client>;
        logger: func() -> option<logger>;
        annotator: func() -> option<annotator-client>;
        local-storage: func() -> option<local-storage-client>;
    }

    /// A type used to limit the scope in which granted capabilities can be used.
    /// Used primarily to filter events before more expensive processing and overhead 
    /// (such as instantiating and executing WASM components), but can also be used to limit
    /// the context in which certain capabilities (like local storage) can be used.
    record capability-scope {
        /// A CEL expression to match against context in which the capability is used,
        /// determining whether the capability applies.
        expression: string,
    }

    variant event-kind {
        /// The associated capability determines which connections should be intercepted by the proxy (necessary for receiving any request/response events related to the connection)
        connect,
        // The associated capability determines which HTTP requests should be handled by the plugin
        request,
        // The associated capability determines which HTTP responses should be handled by the plugin
        response,
        // The associated capability determines which inbound content should be handled by the plugin
        inbound-content,
    }

    variant capability-kind {
        /// A capability to handle specific events
        handle-event(event-kind),
        /// A capability to log messages
        logger,
        /// A capability to annotate content (extract and store features + metadata) 
        annotator,
        /// A capability to store local key-value pairs
        local-storage,
    }

    /// A capability requested by the plugin
    record capability {
        /// The kind of capability being requested
        kind: capability-kind,
        /// The scope in which the capability applies (may be modified by the user)
        scope: capability-scope,
    }

    type keyed-values = tuple<string, list<string>>;
    type request-query = keyed-values;
    type request-header = keyed-values;

    record request-context {
        scheme: string,
        host: string,
        path: string,
        query: list<request-query>,
        method: string,
        headers: list<request-header>,
    }

    record contextual-response {
        response: response,
        // TODO: turn request-context into a resource to avoid copying and modifications
        request: request-context,
    }

    /// The different types of events and their associated data that can be handled by plugins
    variant event-data {
        connect,
        request(request),
        response(contextual-response),
        inbound-content(content),
    }

    /// A work-in-progress resource representing abstract content
    /// Primarily exists to abstract away any compression and encoding details
    /// of the underlying body, providing a simple interface for plugins to interact with
    /// without worrying about conflicting or wasteful transformations.
    resource content {
        /// Returns the content as a stream of UTF-8 encoded text
        data: func() -> stream<u8>;
        /// Returns the content type of the content, ex: "text/html; charset=utf-8"
        content-type: func() -> string;
        /// Replace the content body with new stream of UTF-8 encoded text
        set-data: func(data: stream<u8>);
    }
}

interface witm-plugin {
    use capabilities.{capability, capability-provider, event-data};

    record tag {
        key: string,
        value: string,
    }

    /// A manifest describing the plugin, any requested capabilities, and metadata.
    record plugin-manifest {
        /// The name of the plugin
        name: string,
        /// The plugin author's namespace (use for scoping)
        namespace: string,
        /// The publishing plugin author
        author: string,
        /// The plugin version
        version: string,
        /// A short description of the plugin
        description: string,
        /// The plugin license
        license: string,
        /// The plugin homepage URL
        url: string,
        /// The plugin public key (for verifying the plugin)
        publickey: list<u8>,
        /// The capabilities requested by the plugin
        capabilities: list<capability>,
        /// Additional plugin metadata
        metadata: list<tag>,
    }

    /// Returns the plugin manifest
    manifest: func() -> plugin-manifest;

    /// Handles an event
    handle: func(ev: event-data, cp: capability-provider) -> option<event-data>;
}

world plugin {
    import capabilities;
    export witm-plugin;
}