name = "contact-form-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[env.production]
name = "contact-form-worker"

[vars]
ENVIRONMENT = "production"

# Rate limiting bindings
[[unsafe.bindings]]
name = "IP_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 1, period = 60 }

# Add your secrets:
# wrangler secret put EMAIL_USERNAME
# wrangler secret put EMAIL_PASSWORD
# wrangler secret put TURNSTILE_SECRET_KEY
# wrangler secret put RECIPIENT_EMAIL (optional)