# GoReleaser configuration for @ezdev/shared NPM package
version: 2

project_name: ezdev-shared

before:
  hooks:
    - pnpm install --frozen-lockfile
    - pnpm run build

builds:
  - skip: true

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - dist/**/*
      - package.json
      - README.md

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
  name_template: "@ezdev/shared v{{ .Version }}"
  header: |
    ## @ezdev/shared v{{ .Version }}
    
    Release of the shared validation schemas and utilities for ezdev projects.

publishers:
  - name: npm
    cmd: npm publish --access public
    env:
      - NODE_AUTH_TOKEN={{ .Env.NODE_AUTH_TOKEN }}

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

git:
  tag_sort: -version:refname

snapshot:
  name_template: "{{ incpatch .Version }}-next"