name: Deploy Contact Form Worker

on:
  push:
    branches: [main]
    paths:
      - 'src/apps/contact-form-worker/**'
      - 'src/typescript/shared/**'
      - '.github/workflows/contact-form-worker-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Contact Form Worker
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '*'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: src/apps/contact-form-worker
        run: pnpm install --frozen-lockfile

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: src/apps/contact-form-worker
          command: deploy