name: Test Contact Form Worker

on:
  push:
    branches: [main]
    paths:
      - 'src/apps/contact-form-worker/**'
      - 'src/typescript/shared/**'
      - 'src/apps/contact-form-worker/.github/test.yml'
      - '.github/workflows/contact-form-worker-test.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/apps/contact-form-worker/**'
      - 'src/typescript/shared/**'
      - 'src/apps/contact-form-worker/.github/test.yml'
      - '.github/workflows/contact-form-worker-test.yml'

jobs:
  test:
    uses: ./src/apps/contact-form-worker/.github/test.yml