name: Test Contact Form Worker

on:
  push:
    branches: [main]
    paths:
      - 'src/apps/contact-form-worker/**'
      - 'src/typescript/shared/**'
      - '.github/workflows/contact-form-worker-test.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/apps/contact-form-worker/**'
      - 'src/typescript/shared/**'
      - '.github/workflows/contact-form-worker-test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Contact Form Worker
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '*'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        working-directory: src/apps/contact-form-worker
        run: pnpm typecheck

      - name: Run tests
        working-directory: src/apps/contact-form-worker
        run: pnpm test:run