name: Deploy ezco-web to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'src/apps/ezco-web/**'
      - 'src/typescript/shared/**'
      - '.github/workflows/ezco-web-deploy.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '*'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: 
          pnpm i

      - name: Build with Astro
        run: |
          pnpm build:ezco-web

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/apps/ezco-web/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4