name: Build ezdev-web

on:
  push:
    branches:
      - main
    paths:
      - 'src/apps/ezdev-web/**'
      - 'src/typescript/shared/**'
      - 'src/apps/ezdev-web/.github/build.yml'
      - '.github/workflows/ezdev-web-build.yml'
  pull_request:
    paths:
      - 'src/apps/ezdev-web/**'
      - 'src/typescript/shared/**'
      - 'src/apps/ezdev-web/.github/build.yml'
      - '.github/workflows/ezdev-web-build.yml'

jobs:
  build:
    uses: ./src/apps/ezdev-web/.github/build.yml