name: Build @ezdevlol/shared

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/typescript/shared/**'
      - '.github/workflows/ezdev-shared-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/typescript/shared/**'
      - '.github/workflows/ezdev-shared-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '*'
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15'
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build shared library
        run: pnpm --filter @ezdevlol/shared build
        
      - name: Type check
        run: pnpm --filter @ezdevlol/shared typecheck
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shared-dist
          path: src/typescript/shared/dist/
          retention-days: 7