attic:
    env: ENC[AES256_GCM,data:ET9U9v3B/n/7XsRhezRTSfP6w9HnHTnqy0Rwwb3JJMKKYhicMYcz1c5SRlSiHcilsRi2lR/2Uw1qG50As2zU3Pk964yIVIhUgPjCEvLSFv2Kldw+8K4y4oc208jVbjgkCEg5dJP/dtWeM1LImC8pXereTuSKjCuQyLf+E4fwGA==,iv:AzVyPeXGiDUGc9bXMHhOzCa6lBZmS1ut+nx9Ya04eio=,tag:V6qsMENZGtqocZ/JK5A9UQ==,type:str]
    token-ci: ENC[AES256_GCM,data:TTlrjMy3Gpg6SrrY4Eqw92hlgycohb7a0b3N50XBIPZ9Dv4lRxmZalhoij2UBrxIociJykvGioJxUSqxvbN7LUBn679TANeUqwVFZqMXnKKk8eaFFjZnj2Cz8KkYPErPisi8lfZ39I9fnsKgDmR52mKXyyQcSjSmtZqIE1uDWXHEuug5nL6gRJy+i5wdW0sEEXs+pkNeToH/R4w/DKYvqPx9+PNHWIVdgMXw2bmVUz+Qk6hXuFFVgnpUsRKqMSbsT2wtqvvSVFRoZ9eU4wPSTrKLNGG8KWA=,iv:9iGbkrOvt1bCVklt4zmMv/3mz5P/dr5uffZoZ9oeXz0=,tag:DAY3HWkPJ8SdkAYRP2c4Mg==,type:str]
    token-ci-trusted: ENC[AES256_GCM,data:hBtkGf+98zk9YH9BMzqvJcOGRRm9zwnMVqO2qVObMEzULFwP9KvDx2ndw3GOLqPxO7KhS5FijoZpT15r6N8fZq8v+pXmyCM1l1aqHrxOKp+E7AQy97Nwd+addLoTJd6dAva7MzfVTzWAB96/2TxwxP+1nKAWo8rIhuiEhl5togf5q5dSj2V0xvBscAQlsGi59tSGJGDCvZSI62TqUSvGHs35gr6V97CJdUvPAQ1tihW71CE7b3Xz0OOz21EPs1M6/D7IJnJjDsCYoyx4g+PX8QxclW8CI/2WkPXWUjf41r5F1vbOwwi9FnKk7fxcZ7g74V/j,iv:/Y3SJP0nAACs+rjWVBl0O6VHZybZbH1CF0gtiMe5sjM=,tag:/diDs/GHqV1HEOKKKLv+Zw==,type:str]
github:
    runner-pat: ENC[AES256_GCM,data:8npJ1fld+/kLtUaol0Gl9Bg1fll3uqb8P+dzEGSYJby+4CCoB+bay4c86pG3UcylAA0BdEhqby7i6T4YDnf5jvGOjwPZjPg6CVbX8AfhRp5vyptMuZhxd7KpV63y,iv:0rqJE9ejrzD0LrFhGC5SRYjdQyHv1jGtnQCwK4KgGds=,tag:0BJUfAk7VhwpxK8Ra0LPgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQR1BOUW1TNGFnc0paSlVH
            MzhRcVVlMlkxR3JWVkZVN3pWZGxIS0pvRTJ3CjZvUkxQbm1MZnFxa0E0YlYyWTN6
            K2RYUFpUOWY2elBNMlI3WFpLci92d1UKLS0tIEVQTjIvc0pVSnNiWVlTVWJDUW9V
            S0NTRGlpL2FrYjJrYllzYnJTZjgvdUUKt5DH1hAyWobfzSWW6SKRaIQo2nDL/CJE
            TYyJXnELJkfOPP/cETFkS2vck+mX4lmFP/pQKtS8OUQrN3NyAFVnIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16rm7c0uhkwv68wevajy6u0naj7er203lednsa44j3yk9vgngdsjqa47m69
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VEg3YzgzNUtsOFplVTBS
            UGJuWlpjcEFXYUlHRjJNUUR6ay83RW5iRURnClNhcHdTcXh0TTc2ZFpwaU9TNzFX
            WVdaU3FBUzBBTDNkd0x4bDlsRlZ2ZmcKLS0tICtJblZWK01KVm1FWjVKUjExSlFq
            VC8rVXZpNnhjSE5kdmNQdVJVd1pCdE0Ka04C39wkak3x4V8VchPCLPyEK9E0jSAt
            AmmSsh9Glvrej/2xcggjEYoaYFD1ulDPe2t38SrUCGzNEc1RbuZxCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16m2djdwszt7k7nnjq6lrxaykaxkvpqwvu80mr2s05gzh3lkqs5aqzr5l5v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRC9HQy9DUU5MKys5ckpx
            dmZYemRxdktHZ0o2ejdlcyt6NVVUZlhWM1dNCmJ2US84QmlOUkQvbmNiZFdOVmJL
            eDlHdm5HQzVNaWxERnZuZURTRTBxN0EKLS0tICtWZHNVSlJhRnBJL1pyanFveTNZ
            UVdTcFBKTEx1NkhXMjNjMmVrQi9JMkkK172sWqZR1xs1ovQZCS19VFmKxd3OTusX
            +SX9cqyMzosnWt4wTZpVHSkQXBxCQH6wVWSNhezkKr82AmHPrpY2lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyfnntzkmsk7ylzct4hu74nk2vfltdl7895a8zugmkcn4zltt9ds63rt0g
    lastmodified: "2026-09-30T02:36:19Z"
    mac: ENC[AES256_GCM,data:S9ad9xiOxej8mlFVkfcEjvj9O04PmJ+Tlic/gWpna3k9N2wIuN+1xcpDolHsGw0Usodyv4gBo2qblY3w6FEQPqK+aio3qoxd38/B+aPiKVjDLu0QKLr11tWVlXYOt500/uA4U7HBddWA96tUFxtMHZ0fyjNMh6Us54oCiUB+JZU=,iv:9HnFKhti6PwfIgO9HZTtwI2N/BY/LYynMAEDDdWr2yI=,tag:LmLpB4hvNtt/LTBvcpW7uw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
